inertial_frame_id: world
waypoints:

  -
    point: [0, 0, -10]
    max_forward_speed: 10.0
    heading: 0
    use_fixed_heading: False
  # -
  #   point: [0, 0, 0]
  #   max_forward_speed: 10.0
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [0, 0, 0]
  #   max_forward_speed: 10.0
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [-3, 3, 0]
  #   max_forward_speed: 1.0
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [-3, -3, 0]
  #   max_forward_speed: 1.0
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [3, -3, 0]
  #   max_forward_speed: 1.0
  #   heading: 0
  #   use_fixed_heading: False